### PR TITLE
Generalize opts_present() and opts_str() for any iterator over strings

### PR DESCRIPTION
**Pull request by t-rapp**
Makes these functions more ergonomic to use with string slices.

### CODE REVIEW

**Comment by t-rapp** [comment]
Both functions should still accept arguments of type `&[String]` so backwards compatibility should be provided. Do you suggest that type inference can be a problem here (besides the case with `&[]` in the tests which I think is unlikely in production code)? I tried to follow the path in commit c513d54.

**Comment by t-rapp** [comment]
Maybe a less problematic solution could be:

    pub fn opts_present<T: AsRef<str>>(&self, names: &[T]) -> bool { ... }
    pub fn opts_str<T: AsRef<str>>(&self, names: &[T]) -> Option<String> { ... }

it would still allow using `m.opts_present(&["foo", "bar"])` instead of the current `m.opts_present(&["foo".to_string(), "bar".to_string()])` which was the situation I wanted to optimize for. What do you think?

**Comment by alexcrichton** [comment]
Yeah the breakage I'm worried about is around inference, and `&[]` is one way for that to arise. I agree it's a good idea to avoid the unnecessary `to_string` though!

I think though that `&[T]` still runs into the same issue because if called with `&[]` it can't figure out what `T` is

**Comment by t-rapp** [comment]
Concerns regarding API breakage understood. Have added new functions `opts_present_any` and `opts_str_first` instead. I'm open to any name (or code) improvement suggestions.

**Comment by alexcrichton** [comment]
Seems reasonable to me, thanks!

**Pull request merged**
