### PR TITLE
Sfr/optiongrouping

### PR DESCRIPTION
**Pull request by silvio**
This is the second try to get option grouping (#13). It obsoletes #34.
What do you think?

### CODE REVIEW

**Comment by silvio** [comment]
ping @alexcrichton

**Comment by alexcrichton** [comment]
Thanks @silvio! I think the API here may want to be more along the lines of sub-builders rather than add-something-to-the-last-optgroup. That would allow further configuration of the option group, and I was also expecting options to perhaps be defined in terms on the option groups rather than through the normal builder still?

**Comment by wackywendell** [comment]
Hello! @silvio, what are your thoughts on continuing this? How's it going? Just curious!

**Comment by silvio** [comment]
hi @wackywendell,
as I'm new with rust I don't understand fully what @alexcrichton is meaning to me. So I will wait till I understand a little bit more or someone explain me what I have to do. :-)

**Comment by wackywendell** [comment]
Ah! That makes sense! I'm no @alexcrichton, but I hope you don't mind if I take a crack at explaining his suggestion.

@alexcrichton's underlying suggestion is "I think the API here may want to be more along the lines of sub-builders rather than add-something-to-the-last-optgroup."

I think this is best explained by two examples.

Your current method looks something like this:

```rust
// Create a new grouping
opts.optgroup("Group1");
// Add option "foo" to Group1
opts.optflag("f", "foo", "Option foo");
```

So you tell `Options` to create a new group, and then use the standard methods `optflag`, `optflagmulti`, etc. to create a new option to be added to the last group.

Alex is suggesting a different approach, where `optgroup` *returns* some sort of object (a "sub-builder"), and then you call `group.optflag(…)` etc. to add options to the group. Something like this:

```rust
// Create a new grouping
let group = opts.optgroup("Group1");
// Add option "foo" to Group1
group.optflag("f", "foo", "Option foo");
// Add option "bar" to Group1
group.optflag("b", "bar", "Option bar");
// Add option "baz" to no group
opts.optflag("z", "baz", "Option baz");
```

Note that that is an example of what I think @alexcrichton is suggesting, and you don't need to do it precisely that way.

Does that explanation help, @silvio? @alexcrichton, feel free to add / correct me!

**Comment by alexcrichton** [comment]
Ah yes that is indeed what I intended, sorry for the confusion and thanks for the explanation @wackywendell!

**Comment by silvio** [comment]
Ah okay.
I will improve my work for this.

**Comment by steveklabnik** [comment]
This PR no longer merges cleanly.

**Comment by alexcrichton** [comment]
Ah ok, closing out of inactivity, but feel free to resubmit with a rebase!

**Pull request closed without merging**
