### PR TITLE
Optional argument

### PR DESCRIPTION
**Pull request by tromey**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by nox** [comment]
That's a breaking change and should have been bumped as such.

**Comment by KodrAus** [comment]
Identifying logically breaking changes like this is pretty tricky. Just looking at the diff here I can't exactly pinpoint what breakage occurs, but I suspect just about any change to existing behaviour is potentially going to break someone.

@nox do you have any more light to shed or suggestions on how we could manage behavioural changes better?

**Comment by SimonSapin** [comment]
I didn’t look at the diff, but the change of behavior is explained in a commit message:

> This changes the parsing of long options that have optional arguments.
Now the `=` is required; that is, `--arg=something` and `--arg something`
are parsed differently.

This means that a script that passed `--arg something` to a program that uses getopts 0.2.14 will break (not have the intended behavior anymore) when the program updates to getopts 0.2.15.

In https://github.com/servo/servo/pull/21356, this manifested as `error: Service is unavailable: 127.0.0.1:4444` in the web-platform-tests harness.

Hindsight makes saying this much easier to say of course, but I think it should have been readily apparent from the change description that such breakage was possible. It would have been good to discuss that potential in this PR before landing it. Even a single sentence along the lines of “I think breakage will be minimal enough to be acceptable because X and Y” would have shown that this was considered. Although in this case (again, with hindsight) it would have been preferable to conclude that this change should not land without a semver-incompatible version number increment, 0.3.0. (However 0.2.15 has been out long enough that likely doesn’t help to do that increment now.)

**Comment by KodrAus** [comment]
Thanks @SimonSapin, that's a fair assessment. Funnily enough the commit message is the place I didn't look...

We should try to be more mindful of capturing the rationale behind, and weighing up the factors leading to, the landing of any changes.

**Pull request merged**
