### PR TITLE
Sfr/optiongroup and friends

### PR DESCRIPTION
**Pull request by silvio**
Please review my code and if its okay include it to your repository. Please review carefully I'm new in rust.

As @alexcrichton has suggested some more information to this PR.

I have added a example repository [here](https://github.com/silvio/rust-getopts-test).

* The first patch is the base for the other two patches. I introduce a content information for `Opt` and `OptGroup` (named variant) to differ between some modes. The first variant is `OptionGroup` for the current implementation.
* The second patch use the first patch. It introduce a new variant `Separator` and the public accessible function `separator()` which results in a blank line at `usage()` call.
* The third patch add two new functions `description()` and `description_header()` for the new variant `Description` which results in some desciptive text at `usage()` call.

## Example separator:

This ...

```
opts.optflag("R", "recursive", "operate on files and directories recursively");
opts.separator();
opts.optflag("H", "", "if a command line argument is a symbolic link to a directory, traverse it");
```
... results in this:

```
[...]
    -R, --recursive     operate on files and directories recursively

    -H                  if a command line argument is a symbolic link to a
                        directory, traverse it
[...]
```

## Example description*():

This:

```
[...]
opts.optflag("R", "recursive", "operate on files and directories recursively");
opts.description_header("Flags for -R");
opts.description("The following options modify how a hierarchy \
                  is traversed when the -R option is also specified.  \
                  If more than one is specified, only the final one \
                  takes effect.")
opts.optflag("H", "", "if a command line argument is a symbolic link \
                       to a directory, traverse it");
[...]
```

The result is:

```
[...]
    -R, --recursive     operate on files and directories recursively

    Flags for -R:
        The following options modify how a hierarchy is traversed when the -R
        option is also specified. If more than one is specified, only the final
        one takes effect.
    -H                  if a command line argument is a symbolic link to a
                        directory, traverse it
[...]
```

### CODE REVIEW

**Comment by alexcrichton** [comment]
I have a little trouble understanding what's going on here, could you expand the commit PR description to include what this is along with some rationale? It'd also be great to have some tests showcasing the new functionality as well!

**Comment by silvio** [comment]
I have updated the commit message and remove some old examples.

**Comment by alexcrichton** [comment]
Hm ok, interesting! Do you know if other getopts-like implementations have support for things like this? The current implementation seems to go out of its way to ensure that descriptions are formatted correctly, so it seems like it may be worth bolstering up that logic instead of adding new methods?

**Comment by silvio** [comment]
I don't know. A comment on #13 (from steve) looks like that its possible with docopt. But I'm not sure.

Can you give me a hint what's your idea for a better implementation. My first idea (beside this approach) was a new `struct optiongroup` for adding of several options. But I think it takes the flexibility to do some more formatting like a blank line etc...

**Comment by alexcrichton** [comment]
docopt is a little different just because it parses the help string rather than programmatically constructing it. I'm a little hesitant to add a litany of methods just for helping format some descriptions, it also looks like it may be intended for delineating option groups or possibly providing extended help text for an option? 

I was thinking it would be worth perhaps parsing the description of an option for the former case to do some nicer formatting, and then maybe one method could be added for option groups perhaps rather than for "formatting in general"

**Comment by tromey** [comment]
Other option parsers do support option groups.  For example, both glibc's argp and gtk's option parsers support this; as did the older popt.

http://www.gnu.org/software/libc/manual/html_node/Argp-Children.html#Argp-Children
https://developer.gnome.org/glib/stable/glib-Commandline-option-parser.html

IMO it would be better to have child groups handled via grouping objects rather than calls intended to change just the formatting of the help output.

**Comment by silvio** [comment]
Okay - I will rework my patchset at weekend.

**Comment by silvio** [comment]
Closed, replaced by #35

**Pull request closed without merging**
