### PR TITLE
Fix mutable aliasing uncovered by MIR borrow-checking

### PR DESCRIPTION
**Pull request by SimonSapin**
To reproduce, build on Nightly with `RUSTFLAGS=-Znll`

### CODE REVIEW

**Comment by SimonSapin** [comment]
Sorry, I thought this was already fixed in `master` when I opened #60 but I must have made a mistake.

**Comment by alexcrichton** [comment]
Will this be necessary in the long run? Is `[patch]` a viable option in the short term?

**Comment by SimonSapin** [comment]
Yes, I can use `[patch]` to continue testing NLL with Servo’s dependency graph.

However this particular compiler behavior change was ruled in https://github.com/rust-lang/rust/issues/47707 as not a bug, but rather fixing a previous soundness bug. So this change (or something like it) will be needed when NLL is enabled in Nightly by default. Why wait?

**Comment by SimonSapin** [comment]
Telling a soundess fix like this apart from a NLL bug requires manual triaging. Fixing them as we find them will likely help reduce that manual work in future NLL crater runs.

**Comment by alexcrichton** [comment]
Er sorry yeah I didn't realize that this was going to become a hard error in the future! I'm ok merging this for that alone yeah. 

I'm mostly surprised that this wasn't discovered in the previous PR? I think `[patch]` would allow local testing, right? Is the NLL usage in Servo getting committed in that a release is needed to be on crates.io soon?

**Comment by SimonSapin** [comment]
I’ve been trying NLL by running `RUSTFLAGS=-Znll cargo +nightly build`. Nothing’s in the repo.

After seeing that this crate’s build errors was not a rust bug I reproduced it in this repo (not with `[patch]` in servo) at 0.2.14 and 0.2.15 and then saw a successful build at `master` and convinced myself that the issue was already fixed, but I must have run the wrong command for that one.

**Pull request merged**
